CREATE VIEW VIEW_USER_INFORMATION(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTYR, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE) AS
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, CUR.CITY_NAME, CUR.STATE_NAME, CUR.COUNTRY_NAME, HOM.CITY_NAME, HOM.STATE_NAME, HOM.COUNTRY_NAME, PRO.INSTITUTION, EDU.PROGRAM_YEAR, PRO.CONCENTRATION, PRO.DEGREE
FROM USERS U
LEFT JOIN USER_CURRENT_CITIES U_CUR ON U.USER_ID = U_CUR.USER_ID
LEFT JOIN CITIES CUR ON CUR.CITY_ID = U_CUR.CURRENT_CITY_ID
LEFT JOIN USER_HOMETOWN_CITIES U_HOM ON U.USER_ID = U_HOM.USER_ID
LEFT JOIN CITIES HOM ON HOM.CITY_ID=U_HOM.HOMETOWN_CITY_ID
LEFT JOIN EDUCATION EDU ON EDU.USER_ID = U.USER_ID
LEFT JOIN PROGRAMS PRO ON PRO.PROGRAM_ID = EDU.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS(USER1_ID, USER2_ID) AS
SELECT U.USER1_ID, U.USER2_ID
FROM FRIENDS U;

CREATE VIEW VIEW_PHOTO_INFORMATION(ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK) AS
SELECT PH.ALBUM_ID, AB.ALBUM_OWNER_ID, AB.COVER_PHOTO_ID, AB.ALBUM_NAME, AB.ALBUM_CREATED_TIME, AB.ALBUM_MODIFIED_TIME, AB.ALBUM_LINK, AB.ALBUM_VISIBILITY, PH.PHOTO_ID, PH.PHOTO_CAPTION, PH.PHOTO_CREATED_TIME, PH.PHOTO_MODIFIED_TIME, PH.PHOTO_LINK
FROM PHOTOS PH
LEFT JOIN ALBUMS AB ON PH.ALBUM_ID = AB.ALBUM_ID;

CREATE VIEW VIEW_TAG_INFORMATION(PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE) AS
SELECT TG.TAG_PHOTO_ID, TG.TAG_SUBJECT_ID, TG.TAG_CREATED_TIME, TG.TAG_X, TG.TAG_Y
FROM TAGS TG;

CREATE VIEW VIEW_EVENT_INFORMATION(EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME, EVENT_END_TIME) AS
SELECT EVE.EVENT_ID, EVE.EVENT_CREATOR_ID, EVE.EVENT_NAME, EVE.EVENT_TAGLINE, EVE.EVENT_DESCRIPTION, EVE.EVENT_HOST, EVE.EVENT_TYPE, EVE.EVENT_SUBTYPE, EVE.EVENT_ADDRESS, CY.CITY_NAME, CY.STATE_NAME, CY.COUNTRY_NAME, EVE.EVENT_START_TIME, EVE.EVENT_END_TIME
FROM USER_EVENTS EVE
LEFT JOIN CITIES CY ON EVE.EVENT_CITY_ID = CY.CITY_ID
LEFT JOIN USERS U ON U.USER_ID = EVE.EVENT_CREATOR_ID;