ALTER TABLE ALBUMS
DROP CONSTRAINT COVER_PHOTO_CONSTRAINT;
ALTER TABLE PHOTOS
DROP CONSTRAINT ALBUM_CONSTRAINT;
DROP TRIGGER order_friends_pairs;
DROP TABLE TAGS CASCADE CONSTRAINTS;
DROP TABLE PHOTOS CASCADE CONSTRAINTS;
DROP TABLE ALBUMS CASCADE CONSTRAINTS;
DROP TABLE PARTICIPANTS CASCADE CONSTRAINTS;
DROP TABLE USER_EVENTS CASCADE CONSTRAINTS;
DROP SEQUENCE pid;
DROP TRIGGER add_progid;
DROP TABLE EDUCATION CASCADE CONSTRAINTS;
DROP TABLE PROGRAMS CASCADE CONSTRAINTS;
DROP TABLE MESSAGES CASCADE CONSTRAINTS;
DROP TABLE USER_HOMETOWN_CITIES CASCADE CONSTRAINTS;
DROP TABLE USER_CURRENT_CITIES CASCADE CONSTRAINTS;
DROP TRIGGER add_cityid;
DROP SEQUENCE cid;
DROP TABLE CITIES CASCADE CONSTRAINTS;
DROP TABLE FRIENDS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;